{
 "title": "Wärmepumpe, Heizung und Warmwasser",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Dashboard",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Außentemperatur",
     "type": "gauge",
     "gridPos": { "h": 6, "w": 4, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "celsius" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "expr": "se_outside_temperature_celsius", "legendFormat": "Außentemperatur" }
     ]
    },
    {
     "title": "Warmwasserspeicher",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 12, "x": 4, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "celsius" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "se_actual_temperature_dhw_celsius",
       "legendFormat": "Ist"
      },
      { "expr": "se_comfort_temperature_celsius", "legendFormat": "Soll" }
     ]
    }
   ]
  },
  {
   "title": "Umgebung",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "T_out",
     "type": "graph",
     "gridPos": { "h": 6, "w": 10, "x": 0, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "yaxes": [
      { "format": "short", "label": "°C" }
     ],
     "targets": [
      { "expr": "se_outside_temperature_celsius", "legendFormat": "Außentemperatur" }
     ]
    }
   ]
  },
  { "title": "Wärmeerzeugung", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 } },
  {
   "title": "Betriebsstatus",
   "type": "natel-discrete-panel",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 3 },
   "targets": [
    { "expr": "se_operating_status", "legendFormat": "Betriebsstatus" }
   ]
  },
  {
   "title": "Wärmepumpe",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "expr": "se_flow_temperature_hp1_celsius",
     "legendFormat": "Vorlauf"
    },
    {
     "expr": "se_return_temperature_hp1_celsius",
     "legendFormat": "Rücklauf"
    },
    {
     "expr": "se_hot_gas_temperature_hp1_celsius",
     "legendFormat": "Heißgas"
    }
   ]
  },
  {
   "title": "Defrost",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "se_defrost_initiated", "legendFormat": "De-Frost" }
   ]
  },
  {
   "title": "Volumenstrom",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "flowlpm" } },
   "yaxes": [
    { "format": "flowlpm" }
   ],
   "targets": [
    { "expr": "se_flow_rate_liter_per_minute", "legendFormat": "Volumenstrom" }
   ]
  },
  {
   "title": "Druck",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "pressurebar" } },
   "yaxes": [
    { "format": "pressurebar" }
   ],
   "targets": [
    { "expr": "se_high_pressure_hp1_bar", "legendFormat": "Hochdruck" },
    { "expr": "se_low_pressure_hp1_bar", "legendFormat": "Niederdruck" }
   ]
  },
  { "title": "Heizung", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 } },
  {
   "title": "Temperaturen",
   "type": "graph",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "expr": "se_comfort_temperature_heating_circuit_1_celsius",
     "legendFormat": "Komfort Heizung"
    },
    {
     "expr": "se_set_temperature_hk_1_celsius",
     "legendFormat": "Sollwert HK1"
    },
    {
     "expr": "se_actual_temperature_hk_1_celsius",
     "legendFormat": "Istwert HK1"
    },
    {
     "expr": "se_actual_flow_temperature_wp_celsius",
     "legendFormat": "Vorlauf HK1"
    },
    {
     "expr": "se_actual_flow_temperature_nhz_celsius",
     "legendFormat": "Vorlauf Nachheiz HK1"
    }
   ]
  },
  {
   "title": "Warmwasser",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 48 },
   "collapsed": true,
   "panels": [
    {
     "title": "Temperaturen",
     "type": "graph",
     "gridPos": { "h": 12, "w": 24, "x": 0, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "celsius" } },
     "yaxes": [
      { "format": "celsius" }
     ],
     "targets": [
      { "expr": "se_comfort_temperature_celsius", "legendFormat": "Komfort Warmwasser" },
      {
       "expr": "se_set_temperature_hk_1_celsius",
       "legendFormat": "Sollwert HK1"
      },
      {
       "expr": "se_actual_temperature_hk_1_celsius",
       "legendFormat": "Istwert HK1"
      },
      {
       "expr": "se_actual_flow_temperature_wp_celsius",
       "legendFormat": "Vorlauf HK1"
      },
      {
       "expr": "se_actual_flow_temperature_nhz_celsius",
       "legendFormat": "Vorlauf Nachheiz HK1"
      },
      {
       "expr": "se_actual_temperature_dhw_celsius",
       "legendFormat": "Istwert Warmwasserspeicher"
      }
     ]
    }
   ]
  },
  {
   "title": "Energieaufnahme",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 49 },
   "collapsed": true,
   "panels": [
    {
     "title": "pro Tag",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 6 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "se_vd_dhw_day_power_consumption_hp1_kilo_watt_hour",
       "legendFormat": "Warmwasser"
      },
      {
       "expr": "se_vd_heating_day_power_consumption_hp1_kilo_watt_hour",
       "legendFormat": "Heizung"
      }
     ]
    }
   ]
  }
 ]
}